### ISSUE TITLE
Build Error, version compatibility

### ISSUE THREAD

**Issue by jmyvalour** [TileDB-Inc/TileDB-MariaDB#363]
Hello,

Trying to build and test tildb mariadb plugin on Ubuntu 22.

Following this documentation https://docs.tiledb.com/main/integrations-and-extensions/sql/mariadb/installation-from-source#compiling, 
Current master is not able to build with mariadb version 10.5, getting compilation error, I updated to mariadb 11.1.6 and it works well. 

Now that the build is working file, I get the a segfault server-side when trying to create a new array: 

create table test_array (   dim0 integer DIMENSION=1 lower_bound="0" upper_bound="100" tile_extent="10",   dim1 integer DIMENSION=1 lower_bound="0" upper_bound="100" tile_extent="10",   attr1 varchar(255) filters="GZIP=-1" ) engine=MyTile array_type='SPARSE' coordinate_filters="NONE" offset_filters="POSITIVE_DELTA=128";

> 0x00007ffff41025ae in tile::mytile::mytile(handlerton*, TABLE_SHARE*) () from /lib/plugin/ha_mytile.so
> (gdb) bt
> #0  0x00007ffff41025ae in tile::mytile::mytile(handlerton*, TABLE_SHARE*) () from lib/plugin/ha_mytile.so
> #1  0x00007ffff41133dd in mytile_create_handler(handlerton*, TABLE_SHARE*, st_mem_root*) () from lib/plugin/ha_mytile.so
#2  0x00005555562d15d5 in get_new_handler(TABLE_SHARE*, st_mem_root*, handlerton*) ()
#3  0x000055555660c99e in mysql_create_frm_image(THD*, HA_CREATE_INFO*, Alter_info*, int, st_key**, unsigned int*, st_mysql_const_unsigned_lex_string*) ()
#4  0x000055555660f75c in create_table_impl(THD*, st_ddl_log_state*, st_ddl_log_state*, st_mysql_const_lex_string const&, st_mysql_const_lex_string const&, st_mysql_const_lex_string const&, st_mysql_const_lex_string const&, st_mysql_const_lex_string const&, DDL_options_st, HA_CREATE_INFO*, Alter_info*, int, bool*, st_key**, unsigned int*, st_mysql_const_unsigned_lex_string*) ()
#5  0x000055555660f088 in mysql_create_table_no_lock(THD*, st_ddl_log_state*, st_ddl_log_state*, Table_specification_st*, Alter_info*, bool*, int, TABLE_LIST*) ()

started the test but get an error too:

worker[01] Using MTR_BUILD_THREAD 300, with reserved ports 19000..19029
mytile.1st                               [ pass ]      1
mytile.2nd                               [ fail ]

> libc_sigaction.c:0(__restore_rt)[0x7a3e9b442520]
>/mysql-test/var/plugins/ha_mytile.so(_ZN4tile6mytileC2EP10handlertonP11TABLE_SHARE+0x2e)[0x7a3e9693e5ae]
> ha_mytile.cc:0(mytile_create_handler(handlerton*, TABLE_SHARE*, st_mem_root*))[0x7a3e9694f3dd]

Is there any version I should use to have it working ? Any idea, advice would be  helpful,

Thanl you,

**Comment by DimitrisStaratzis** [comment]
Hi @jmyvalour,
Thank you for opening the issue. Our master branch supports MariaDB 11.0.2. Let us know if you are able to build and run successfully with that version.

**Comment by DimitrisStaratzis** [comment]
Thanks! We will update the README and docs to avoid confusion in the future.
